apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: configmapgroup
spec:
  schema:
    apiVersion: v1alpha1
    kind: ConfPool
    spec:
      confs: "[]string"
      data: string
  resources:
    - id: configMaps
      forEach:
        - conf: ${schema.spec.confs}
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${schema.metadata.name + "-" + conf}
          namespace: default
        data:
          data: ${schema.spec.data}
